<?xml version="1.0" encoding="utf-8"?><Database Name="Proizvodi" Class="ProizvodiDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-BCQJUAM\LUKADOGANDZIC;Initial Catalog=Proizvodi;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ProizvodiConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Proizvod" Member="Proizvods">
    <Type Name="Proizvod">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Naziv" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Opis" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Kategorija" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Proizvodjac" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Dobavljac" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Cena" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>